language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - sudo apt-get update
  - sudo apt-get install -qq bioperl apache2 libapache2-mod-perl2 libapache2-mod-perl2-dev libapreq2 libapache2-request-perl
  - cpanm -v --installdeps --notest --skip-satisfied .
