language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - sudo apt-get install -qq libdb-dev graphviz libgd2-xpm-dev libxml2-dev bioperl apache2 libapache2-mod-perl2 libapreq2 libapache2-request-perl
  - cpanm --quiet --installdeps --notest .
