VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210.box"
    config.vm.box = "biovel-nbc-fedora-18"
    config.vm.host_name = "biovel-nbc"
    config.vm.provision "puppet"
    config.vm.network "forwarded_port", guest: 80,  host: 4567
end