VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.box = "biovel-nbc-ubuntu"
    config.vm.host_name = "biovel-nbc"
    config.vm.provision "puppet"
    config.vm.network "forwarded_port", guest: 80,  host: 4567
end